from __future__ import annotations

from typing import Final

CONCEPT_IDS: Final[frozenset[str]] = frozenset(
    {
        "function",
        "loop",
        "condition",
        "class",
        "variable",
        "recursion",
        "map",
        "filter",
        "sort",
        "reduce",
        "file_io",
        "exception",
        "import",
        "lambda",
        "comprehension",
        "io",
        "nested_loops",
    }
)

CONSTRUCTION_TO_CONCEPTS: dict[str, tuple[str, ...]] = {
    "for_loop": ("loop",),
    "while_loop": ("loop",),
    "nested_loops": ("nested_loops",),
    "loop": ("loop",),
    "foreach": ("loop",),
    "recursion": ("recursion",),
    "if_statement": ("condition",),
    "cond": ("condition",),
    "condition": ("condition",),
    "exception": ("exception",),
    "function_definition": ("function",),
    "function_def": ("function",),
    "function": ("function",),
    "return_statement": ("function",),
    "return": ("function",),
    "method": ("function",),
    "method_call": ("function",),
    "direct_call": ("function",),
    "chained_call": ("function",),
    "call": ("function",),
    "io": ("io",),
    "lambda": ("lambda",),
    "binary_expression": ("variable",),
    "identifier": ("variable",),
    "arith": ("variable",),
    "assign": ("variable",),
    "assignment": ("variable",),
    "variable": ("variable",),
    "map": ("map",),
    "filter": ("filter",),
    "reduce": ("reduce",),
    "comprehension": ("comprehension",),
    "sort": ("sort",),
    "file_io": ("file_io",),
    "class": ("class",),
    "import": ("import",),
}
